extends: [[spectral:oas, all]]

overrides:
  - files:
      - "**#/components/schemas/Activity/properties/tags/example"
    rules:
      oas3-valid-schema-example : "info"
  # neither works
#  - files:
#      - "openapi.json#/components/schemas/Activity/properties/tags/example"
#    rules:
#      oas3-valid-schema-example: "info"
